import AppKit
import Combine
import Foundation

@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let store = ClipboardHistoryStore()
    private let settings = ClipboardSettingsStore.shared
    private var cancellables = Set<AnyCancellable>()
    private(set) var entries: [ClipboardEntry] = []
    var onChange: (() -> Void)?

    private let privatePasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    init() {
        Publishers.CombineLatest3(
            settings.$historyLimit,
            settings.$retentionDays,
            settings.$excludedBundleIDs
        )
        .dropFirst()
        .sink { [weak self] _ in
            self?.applyPolicy()
        }
        .store(in: &cancellables)
    }

    func start() {
        guard timer == nil else { return }
        entries = store.load()
        applyPolicy()
        onChange?()
        let timer = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.readPasteboard() }
        }
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() {
        entries.removeAll()
        store.clear()
        onChange?()
    }

    func pollNow() {
        readPasteboard()
    }

    @discardableResult
    func writeToPasteboard(entryID: UUID) -> Bool {
        guard let entry = entries.first(where: { $0.id == entryID }) else { return false }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        let succeeded: Bool
        if let imageData = entry.imageData, let image = NSImage(data: imageData) {
            let pngWritten = pasteboard.setData(imageData, forType: .png)
            let tiffWritten = image.tiffRepresentation.map {
                pasteboard.setData($0, forType: .tiff)
            } ?? false
            succeeded = pngWritten || tiffWritten
        } else {
            succeeded = pasteboard.setString(entry.value, forType: .string)
        }

        lastChangeCount = pasteboard.changeCount
        return succeeded
    }

    func togglePinned(entryID: UUID) {
        guard let index = entries.firstIndex(where: { $0.id == entryID }) else { return }
        entries[index].isPinned.toggle()
        applyPolicy(notify: false)
        store.save(entries)
        onChange?()
    }

    func recordCurrentImage(sourceName: String) {
        let pasteboard = NSPasteboard.general
        lastChangeCount = pasteboard.changeCount
        guard let imageData = imageData(from: pasteboard) else { return }
        insertImage(
            imageData,
            sourceBundleID: Bundle.main.bundleIdentifier,
            sourceName: sourceName
        )
        applyPolicy(notify: false)
        store.save(entries)
        onChange?()
    }

    private func readPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let availableTypes = Set(pasteboard.types ?? [])
        guard availableTypes.isDisjoint(with: privatePasteboardTypes) else { return }

        let capturedImageData = imageData(from: pasteboard)
        let sourceApplication = NSWorkspace.shared.frontmostApplication
        let sourceBundleID = sourceApplication?.bundleIdentifier
        let isKnotCapture = sourceBundleID == Bundle.main.bundleIdentifier
            && capturedImageData != nil
        guard isKnotCapture || (sourceBundleID.map({ !isExcluded($0) }) ?? true) else { return }
        if let imageData = capturedImageData {
            insertImage(
                imageData,
                sourceBundleID: sourceBundleID,
                sourceName: sourceApplication?.localizedName
            )
        } else if let value = pasteboard.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines),
                  !value.isEmpty {
            let wasPinned = entries.first(where: {
                $0.imageData == nil && $0.value == value
            })?.isPinned ?? false
            entries.removeAll { $0.imageData == nil && $0.value == value }
            entries.insert(
                ClipboardEntry(
                    value: value,
                    sourceBundleID: sourceBundleID,
                    sourceName: sourceApplication?.localizedName,
                    isPinned: wasPinned
                ),
                at: 0
            )
        } else {
            return
        }
        applyPolicy(notify: false)
        store.save(entries)
        onChange?()
    }

    private func applyPolicy(notify: Bool = true) {
        let previous = entries
        if settings.retentionDays > 0 {
            let cutoff = Calendar.current.date(
                byAdding: .day,
                value: -settings.retentionDays,
                to: Date()
            ) ?? .distantPast
            entries.removeAll { !$0.isPinned && $0.copiedAt < cutoff }
        }
        entries.removeAll(where: shouldExclude)
        let pinned = entries.filter(\.isPinned).sorted { $0.copiedAt > $1.copiedAt }
        let regularLimit = max(0, settings.historyLimit - pinned.count)
        let regular = entries
            .filter { !$0.isPinned }
            .sorted { $0.copiedAt > $1.copiedAt }
            .prefix(regularLimit)
        entries = pinned + regular

        guard entries != previous else { return }
        store.save(entries)
        if notify { onChange?() }
    }

    private func isExcluded(_ bundleID: String) -> Bool {
        bundleID == "app.baomi.knot" || settings.excludedBundleIDs.contains(bundleID)
    }

    private func shouldExclude(_ entry: ClipboardEntry) -> Bool {
        if entry.isImage, entry.sourceBundleID == Bundle.main.bundleIdentifier {
            return false
        }
        return entry.sourceBundleID.map(isExcluded) ?? false
    }

    private func insertImage(
        _ imageData: Data,
        sourceBundleID: String?,
        sourceName: String?
    ) {
        let wasPinned = entries.first(where: { $0.imageData == imageData })?.isPinned ?? false
        entries.removeAll { $0.imageData == imageData }
        entries.insert(
            ClipboardEntry(
                value: "",
                imageData: imageData,
                sourceBundleID: sourceBundleID,
                sourceName: sourceName,
                isPinned: wasPinned
            ),
            at: 0
        )
    }

    private func imageData(from pasteboard: NSPasteboard) -> Data? {
        guard let image = sourceImage(from: pasteboard) else { return nil }

        let sourceSize = image.size
        guard sourceSize.width > 0, sourceSize.height > 0 else { return nil }
        let maximumDimension: CGFloat = 2_048
        let scale = min(1, maximumDimension / max(sourceSize.width, sourceSize.height))
        let width = max(1, Int((sourceSize.width * scale).rounded()))
        let height = max(1, Int((sourceSize.height * scale).rounded()))

        guard let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: width,
            pixelsHigh: height,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }

        bitmap.size = NSSize(width: width, height: height)
        NSGraphicsContext.saveGraphicsState()
        defer { NSGraphicsContext.restoreGraphicsState() }
        guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else { return nil }
        NSGraphicsContext.current = context
        image.draw(
            in: NSRect(x: 0, y: 0, width: width, height: height),
            from: .zero,
            operation: .copy,
            fraction: 1
        )
        context.flushGraphics()
        guard let png = bitmap.representation(using: .png, properties: [:]),
              png.count <= 12 * 1_024 * 1_024 else { return nil }
        return png
    }

    private func sourceImage(from pasteboard: NSPasteboard) -> NSImage? {
        if let image = NSImage(pasteboard: pasteboard) {
            return image
        }

        let imageTypes: [NSPasteboard.PasteboardType] = [
            .png,
            .tiff,
            NSPasteboard.PasteboardType("public.jpeg"),
            NSPasteboard.PasteboardType("public.heic"),
            NSPasteboard.PasteboardType("com.compuserve.gif")
        ]
        for item in pasteboard.pasteboardItems ?? [] {
            for type in imageTypes {
                if let data = item.data(forType: type), let image = NSImage(data: data) {
                    return image
                }
            }
        }

        let options: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true
        ]
        let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL]
        return urls?.lazy.compactMap { NSImage(contentsOf: $0) }.first
    }
}
